# Generated by Django 3.1.2 on 2020-11-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201101_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
