# Generated by Django 3.1.2 on 2020-11-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogcomment_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='abc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
