# Generated by Django 3.1.2 on 2020-11-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcomment_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='abc',
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
